### PR TITLE
feat(upsert_pipeline): Using gate when upserting pipeline.

### PR DESCRIPTION
**Pull request by DanielaS12**
### Summary of Changes

Ticket: https://armory.atlassian.net/browse/CDSH-231

### PR Checklist

Make sure the following checklist items are done before merging this PR.

- [x] Update `CHANGELOG.md` in the `## Unreleased` section ([instructions here])
- [x] Make sure tests are passing

[instructions here]: https://keepachangelog.com/en/1.0.0/#how

### CODE REVIEW

**Review by kkotula — APPROVED** [review]
Looks good to me!

**Review by ovidiupopa07 — CHANGES_REQUESTED** [review]
instead of going through gate lets call Orca directly. Going through the API gateway when calling an internal service doesn't make sense. Instead let's do the same as gate in `com.netflix.spinnaker.gate.controllers.PipelineController#savePipeline`(calling /ops endpoint)

**Comment by kkotula** [comment]
> instead of going through gate lets call Orca directly. Going through the API gateway when calling an internal service doesn't make sense. Instead let's do the same as gate in `com.netflix.spinnaker.gate.controllers.PipelineController#savePipeline`(calling /ops endpoint)

My understanding was that the endpoint, that would do the job, is not available. If it is, then, of course, let's use it!

**Comment by ovidiupopa07** [comment]
> > instead of going through gate lets call Orca directly. Going through the API gateway when calling an internal service doesn't make sense. Instead let's do the same as gate in `com.netflix.spinnaker.gate.controllers.PipelineController#savePipeline`(calling /ops endpoint)
> 
> My understanding was that the endpoint, that would do the job, is not available. If it is, then, of course, let's use it!

We don't have an endpoint in Orca specific to the save pipeline functionality. We can reuse the `/ops` endpoint that is being used to submit new operations. This is the same thing Gate is doing when saving a pipeline.

**Comment by ovidiupopa07** [comment]
Looks ok to me but I would like to see some screenshots showing that everything works in dinghy (saving/updating pipelines)

**Comment by DanielaS12** [comment]
> It looks ok to me, but I would like to see some screenshots showing that everything works in dinghy (saving/updating pipelines)
> 
> 1. Change/create a dinghyfile in a github repo
> 2. Proof that the pipeline is created and later update in Spinnaker (deck screenshots)

Tested locally both cases of save and update - everything works as expected:
Pasted Graphic 1
Pasted Graphic 2
Pasted Graphic 3

**Review by ovidiupopa07 — APPROVED** [review]
Lgtm

**Pull request merged**
